import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { AutoGeneratedBadge } from './TransactionBadges';

describe('AutoGeneratedBadge', () => {
  it('muestra el texto "Auto"', () => {
    render(<AutoGeneratedBadge />);
    expect(screen.getByText('Auto')).toBeInTheDocument();
  });
});
