import { Trash2, CreditCard, Pencil, Receipt, Loader2 } from 'lucide-react';
import { Button } from '../../../components/ui/button';
import { Card, CardContent } from '../../../components/ui/card';
import { Badge } from '../../../components/ui/badge';
import { CategoryIconBadge } from '../../../components/ui/category-icon';
import { formatCurrency, formatDate, cn } from '../../../lib/utils';
import { getCreditCardPeriod } from '../../../lib/credit-card-utils';
import type { Transaction, Account } from '../../../types';
import { AutoGeneratedBadge } from './TransactionBadges';

interface TransactionCardProps {
  transaction: Transaction;
  accounts: Account[];
  onDelete: (id: string) => void;
  onEdit: (transaction: Transaction) => void;
  onViewItems?: (transaction: Transaction) => void;
  isLoadingItems?: boolean;
}

export function TransactionCard({
  transaction: tx,
  accounts,
  onDelete,
  onEdit,
  onViewItems,
  isLoadingItems = false,
}: TransactionCardProps) {
  const creditCardPeriod = getCreditCardPeriod(
    tx,
    accounts.find((acc) => acc.id === tx.accountId)
  );
  const isCreditCard = accounts.find((acc) => acc.id === tx.accountId)?.type === 'credit_card';

  const itemsLength = tx.receiptItems?.length ?? tx._count?.receiptItems ?? 0;
  const hasReceiptItems = itemsLength > 0;

  return (
    <Card className="transition-all hover:shadow-md">
      <CardContent className="flex items-center justify-between p-4">
        <div className="flex items-center gap-4">
          <CategoryIconBadge
            icon={tx.category?.icon}
            color={tx.category?.color}
            size="lg"
            tooltip={tx.category?.name}
          />
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-medium text-gray-900">{tx.category?.name}</span>
              {tx.fixedExpenseId && <Badge variant="secondary">Fijo</Badge>}
              {tx.isAutoGenerated && <AutoGeneratedBadge />}
              {isCreditCard && tx.type === 'expense' && creditCardPeriod && (
                <Badge variant="outline" className="text-xs">
                  <CreditCard className="mr-1 h-3 w-3" />
                  {creditCardPeriod.label}
                </Badge>
              )}
            </div>
            <p className="text-sm text-gray-500">
              {tx.description || tx.account?.name} • {formatDate(tx.date)}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-4">
          <span
            className={cn(
              'text-base font-semibold',
              tx.type === 'income' ? 'text-green-600' : 'text-red-600'
            )}
          >
            {tx.type === 'income' ? '+' : '-'}
            {formatCurrency(Number(tx.amount))}
          </span>
          {hasReceiptItems && onViewItems && (
            <Button
              variant="ghost"
              size="icon"
              onClick={() => onViewItems(tx)}
              disabled={isLoadingItems}
              className="h-8 w-8 text-gray-500 hover:text-purple-600 pointer"
              title={isLoadingItems ? 'Cargando items...' : `Ver detalle (${itemsLength} items)`}
            >
              {isLoadingItems ? (
                <Loader2 className="h-4 w-4 motion-safe:animate-spin" />
              ) : (
                <Receipt className="h-4 w-4" />
              )}
            </Button>
          )}
          <Button
            variant="ghost"
            size="icon"
            onClick={() => onEdit(tx)}
            className="h-8 w-8 text-gray-500 hover:text-blue-600"
            title="Editar transacción"
          >
            <Pencil className="h-4 w-4" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            onClick={() => onDelete(tx.id)}
            className="h-8 w-8 text-gray-500 hover:text-red-600"
            title="Eliminar transacción"
          >
            <Trash2 className="h-4 w-4" />
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
