import { Zap } from 'lucide-react';
import { Badge } from '../../../components/ui/badge';

export function AutoGeneratedBadge() {
  return (
    <Badge variant="outline" className="border-amber-300 bg-amber-50 text-amber-700 text-xs">
      <Zap className="mr-1 h-3 w-3" />
      Auto
    </Badge>
  );
}
