import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { TransactionCard } from './TransactionCard';
import type { Transaction, Account } from '../../../types';

const account: Account = {
  id: 'acc-1',
  name: 'BBVA',
  type: 'bank',
  balance: 100,
  currency: 'EUR',
  createdAt: '2024-01-01',
};

function makeTx(overrides: Partial<Transaction> = {}): Transaction {
  return {
    id: 'tx-1',
    amount: 25,
    type: 'expense',
    date: '2026-01-05',
    accountId: 'acc-1',
    categoryId: 'cat-1',
    category: { id: 'cat-1', name: 'Comida', icon: null, color: null },
    createdAt: '2026-01-05',
    ...overrides,
  } as Transaction;
}

describe('TransactionCard', () => {
  it('muestra el nombre de la categoría y la descripción', () => {
    render(
      <TransactionCard
        transaction={makeTx({ description: 'Super' })}
        accounts={[account]}
        onDelete={vi.fn()}
        onEdit={vi.fn()}
      />
    );

    expect(screen.getByText('Comida')).toBeInTheDocument();
    expect(screen.getByText(/Super/)).toBeInTheDocument();
  });

  it('llama onEdit/onDelete al hacer click en los botones', async () => {
    const onEdit = vi.fn();
    const onDelete = vi.fn();
    const tx = makeTx();
    const user = userEvent.setup();
    render(
      <TransactionCard transaction={tx} accounts={[account]} onDelete={onDelete} onEdit={onEdit} />
    );

    await user.click(screen.getByTitle('Editar transacción'));
    await user.click(screen.getByTitle('Eliminar transacción'));

    expect(onEdit).toHaveBeenCalledWith(tx);
    expect(onDelete).toHaveBeenCalledWith('tx-1');
  });

  it('muestra el badge de auto-generado cuando corresponde', () => {
    render(
      <TransactionCard
        transaction={makeTx({ isAutoGenerated: true })}
        accounts={[account]}
        onDelete={vi.fn()}
        onEdit={vi.fn()}
      />
    );

    expect(screen.getByText('Auto')).toBeInTheDocument();
  });
});
