import { Trash2, CreditCard, Pencil, Receipt, Loader2 } from 'lucide-react';
import { Button } from '../../../components/ui/button';
import { Badge } from '../../../components/ui/badge';
import { formatCurrency, formatDate, cn } from '../../../lib/utils';
import { getCreditCardPeriod } from '../../../lib/credit-card-utils';
import type { Transaction, Account } from '../../../types';
import { AutoGeneratedBadge } from './TransactionBadges';

interface TransactionRowProps {
  transaction: Transaction;
  accounts: Account[];
  onDelete: (id: string) => void;
  onEdit: (transaction: Transaction) => void;
  onViewItems?: (transaction: Transaction) => void;
  isLoadingItems?: boolean;
}

export function TransactionRow({
  transaction: tx,
  accounts,
  onDelete,
  onEdit,
  onViewItems,
  isLoadingItems = false,
}: TransactionRowProps) {
  const creditCardPeriod = getCreditCardPeriod(
    tx,
    accounts.find((acc) => acc.id === tx.accountId)
  );
  const isCreditCard = accounts.find((acc) => acc.id === tx.accountId)?.type === 'credit_card';

  const itemsLength = tx.receiptItems?.length ?? tx._count?.receiptItems ?? 0;
  const hasReceiptItems = itemsLength > 0;

  return (
    <div className="flex items-center justify-between py-2 hover:bg-gray-50 rounded px-2">
      <div className="flex-1">
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-sm font-medium text-gray-900">
            {tx.description || tx.account?.name}
          </span>
          {tx.fixedExpenseId && (
            <Badge variant="secondary" className="text-xs">
              Fijo
            </Badge>
          )}
          {tx.isAutoGenerated && <AutoGeneratedBadge />}
          {isCreditCard && tx.type === 'expense' && creditCardPeriod && (
            <Badge variant="outline" className="text-xs">
              <CreditCard className="mr-1 h-3 w-3" />
              {creditCardPeriod.label}
            </Badge>
          )}
        </div>
        <p className="text-xs text-gray-500">{formatDate(tx.date)}</p>
      </div>
      <div className="flex items-center gap-2">
        <span
          className={cn(
            'text-sm font-semibold',
            tx.type === 'income' ? 'text-green-600' : 'text-red-600'
          )}
        >
          {tx.type === 'income' ? '+' : '-'}
          {formatCurrency(Number(tx.amount))}
        </span>
        {hasReceiptItems && onViewItems && (
          <Button
            variant="ghost"
            size="icon"
            onClick={() => onViewItems(tx)}
            disabled={isLoadingItems}
            className="h-6 w-6 text-gray-500 hover:text-purple-600"
            title={isLoadingItems ? 'Cargando items...' : `Ver detalle (${itemsLength} items)`}
          >
            {isLoadingItems ? (
              <Loader2 className="h-3 w-3 motion-safe:animate-spin" />
            ) : (
              <Receipt className="h-3 w-3" />
            )}
          </Button>
        )}
        <Button
          variant="ghost"
          size="icon"
          onClick={() => onEdit(tx)}
          className="h-6 w-6 text-gray-500 hover:text-blue-600"
          title="Editar transacción"
        >
          <Pencil className="h-3 w-3" />
        </Button>
        <Button
          variant="ghost"
          size="icon"
          onClick={() => onDelete(tx.id)}
          className="h-6 w-6 text-gray-500 hover:text-red-600"
          title="Eliminar transacción"
        >
          <Trash2 className="h-3 w-3" />
        </Button>
      </div>
    </div>
  );
}
