// Public API of the transactions feature module

// Types
export type {
  TransactionFormData,
  TransactionReceiptItemInput,
  TransactionFilterState,
  TransactionPaginationState,
  TransactionEditInput,
  DateWarning,
} from './types';

// API
export { transactionsApi } from './api';
export type { TransactionApiFilters, CreateTransactionInput, UpdateTransactionInput } from './api';

// Utils
export {
  groupTransactionsByCategory,
  calculatePaginationInfo,
  buildTransactionApiFilters,
  applyClientSideFilters,
  getDefaultTransactionFormData,
  hasActiveFilters,
  DEFAULT_FILTER_STATE,
} from './utils';
export type { GroupedTransaction } from './utils';

// Hooks
export { useTransactions } from './hooks/useTransactions';
export { useTransactionsPage } from './hooks/useTransactionsPage';
export { useTransactionFilters } from './hooks/useTransactionFilters';
export type { TransactionFilters as TransactionFilterValues } from './hooks/useTransactionFilters';
export type { UseTransactionsParams, UseTransactionsReturn } from './hooks/useTransactions';
export type { UseTransactionsPageReturn } from './hooks/useTransactionsPage';

// Components
export { AutoGeneratedBadge } from './components/TransactionBadges';
export { TagBadge } from './components/TagBadge';
export { TagInput } from './components/TagInput';
export { TagSummaryView } from './components/TagSummaryView';
export { TransactionCard } from './components/TransactionCard';
export { TransactionEmpty } from './components/TransactionEmpty';
export { TransactionFilters } from './components/TransactionFilters';
export { TransactionCategorySummaryModal } from './components/TransactionCategorySummaryModal';
export { TransactionList } from './components/TransactionList';
export { TransactionPagination } from './components/TransactionPagination';
export { TransactionRow } from './components/TransactionRow';
export { EditTransactionModal } from './components/EditTransactionModal';
export { ReceiptScanner } from './components/ReceiptScanner';
export { TransactionFormDialog } from './components/TransactionFormDialog';
export type { TransactionFormDialogProps } from './components/TransactionFormDialog';
